### PR TITLE
Updating new sample - cext-trey-research-python

### PR DESCRIPTION
**Pull request by Jegadeesh-MSFT**

### CODE REVIEW

File: samples/cext-trey-research-python/README.md [hunk 1]
```diff
@@ -0,0 +1,178 @@
...
+
+### Setup instructions (one-time setup)
+
+1. Log into Teams Toolkit using the tenant where you will run the sample.
+
+1. Ensure the **Python extension** is installed in Visual Studio Code by searching for 'Python' in the Extensions view (Ctrl+Shift+X) and clicking Install.
+
+1. Press **CTRL+Shift+P** to open the command box and enter **Python: Create Environment** to create and activate your desired virtual environment.
+
+1. If your project doesn't yet have a file **env/.env.local.user**, then create one by copying **env/.env.local.user.sample**. If you do have such a file, ensure it includes these lines.
```
Comment (garrytrinder) [inline samples/cext-trey-research-python/README.md:66]: This line isn't needed, the `file/createOrUpdateEnvironmentFile` task in `teamsapp.local.yml` will be executed when the developer starts a debug session (F5).

**Review by garrytrinder — CHANGES_REQUESTED** [review]
Thanks for the PR @Jegadeesh-MSFT 

Unfortunately, I'm getting errors when starting the function for the first time.

image

Can you take a look?

I'm using `venv` environment, here is the config:

```
home = C:\Users\<user>\AppData\Local\Programs\Python\Python38
include-system-site-packages = false
version = 3.8.10
```

**Comment by Jegadeesh-MSFT** [comment]
Hi @garrytrinder 

The error you're encountering, TypeError: 'type' object is not subscriptable, typically occurs in Python 3.8 when trying to use square-bracket subscripting with types like list[Project], a feature supported only from Python 3.9 onwards.

Please use Python 3.9, 3.10, or 3.11, as version 3.12 is currently not supported for Azure Functions.

File: samples/cext-trey-research-python/appManifest/manifest.json [hunk 2]
```diff
@@ -0,0 +1,44 @@
+{
+  "$schema": "https://developer.microsoft.com/json-schemas/teams/vDevPreview/MicrosoftTeams.schema.json",
+  "manifestVersion": "devPreview",
+  "id": "${{TEAMS_APP_ID}}",
+  "packageName": "com.microsoft.teams.extension",
```
Comment (garrytrinder) [inline samples/cext-trey-research-python/appManifest/manifest.json:5]: Let's remove `packageName` as its not required in 1.19 manifest schema

File: samples/cext-trey-research-python/appManifest/manifest.json [hunk 3]
```diff
@@ -0,0 +1,44 @@
...
+    "short": "Trey Research ${{APP_NAME_SUFFIX}}",
+    "full": "Trey Research consulting management"
+  },
+  "description": {
+    "short": "Everyday management of Trey Research projects and consultants",
+    "full": "This application allows you to find Trey Research projects and consultants, to bill time to a project, and to assign a consultant to a project."
+  },
+  "accentColor": "#FFFFFF",
+  "copilotExtensions": {
+    "declarativeCopilots": [
```
Comment (garrytrinder) [inline samples/cext-trey-research-python/appManifest/manifest.json:27]: Let's update to use `copilotAgents `and `declarativeAgents`

File: samples/cext-trey-research-python/appManifest/manifest.json [hunk 4]
```diff
@@ -0,0 +1,44 @@
...
+      {
+        "id": "treygenie",
+      "file": "trey-declarative-copilot.json"
```
Comment (garrytrinder) [inline samples/cext-trey-research-python/appManifest/manifest.json:30]: Let's replace `copilot` with `agent` in the file name.

File: samples/cext-trey-research-python/appManifest/trey-declarative-copilot.json [hunk 5]
```diff
@@ -0,0 +1,37 @@
+{
+    "$schema": "https://aka.ms/json-schemas/copilot-extensions/vNext/declarative-copilot.schema.json",
```
Comment (garrytrinder) [inline samples/cext-trey-research-python/appManifest/trey-declarative-copilot.json:2]: Let's use the v1.0 schema for declarative agents

https://aka.ms/json-schemas/agent/declarative-agent/v1.0/schema.json

File: samples/cext-trey-research-python/appManifest/trey-declarative-copilot.json [hunk 6]
```diff
@@ -0,0 +1,37 @@
...
+            "title": "Find consultants",
+            "text": "Find trey consultants with a particular skill"
+        }
+    ],
+    "capabilities": [
+        {
+            "name": "OneDriveAndSharePoint",
+            "items_by_url": [
+                {
+                    "url": "https://yourtenantname.sharepoint.com/sites/TreyResearchLegalDocuments"
```
Comment (garrytrinder) [inline samples/cext-trey-research-python/appManifest/trey-declarative-copilot.json:26]: Let's consider using an environment variable here for `yourtenantname`

File: samples/cext-trey-research-python/appManifest/trey-declarative-copilot.json [hunk 7]
```diff
@@ -0,0 +1,37 @@
+{
+    "$schema": "https://aka.ms/json-schemas/copilot-extensions/vNext/declarative-copilot.schema.json",
+    "version": "v1.0",
+    "name": "Trey Genie Local",
+    "description": "You are a handy assistant for consultants at Trey Research, a boutique consultancy specializing in software development and clinical trials. ",
+    "instructions": "Greet users in a professional manner, introduce yourself as the Trey Genie, and offer to help them. Always remind users of the Trey motto, 'Always be Billing!'. Your main job is to help consultants with their projects and hours. Using the TreyResearch action, you are able to find consultants based on their names, project assignments, skills, roles, and certifications. You can also find project details based on the project or client name, charge hours on a project, and add a consultant to a project. If a user asks how many hours they have billed, charged, or worked on a project, reword the request to ask how many hours they have delivered. In addition, you may offer general consulting advice. If there is any confusion, encourage users to speak with their Managing Consultant. Avoid giving legal advice.",
```
Comment (garrytrinder) [inline samples/cext-trey-research-python/appManifest/trey-declarative-copilot.json:6]: Lets use the TTK file function here and move the instructions into a file called `instruction.txt` to align with the out of the box template.

```json
"instructions": "$[file('instruction.txt')]"
```

File: samples/cext-trey-research-python/teamsapp.local.yml [hunk 8]
```diff
@@ -0,0 +1,53 @@
...
+    # Write the information of created resources into environment file for
+    # the specified environment variable(s).
+    writeToEnvironmentFile: 
+      teamsAppId: TEAMS_APP_ID
+
+  # Validate using manifest schema
+  #- uses: teamsApp/validateManifest
+    #with:
+      # Path to manifest template
+      #manifestPath: ./appManifest/manifest.json
```
Comment (garrytrinder) [inline samples/cext-trey-research-python/teamsapp.local.yml:24]: Let's uncomment this action

File: samples/cext-trey-research-python/teamsapp.local.yml [hunk 9]
```diff
@@ -0,0 +1,53 @@
...
+    with:
+      # Path to manifest template
+      manifestPath: ./appManifest/manifest.json
+      outputZipPath: ./appManifest/build/appManifest.${{TEAMSFX_ENV}}.zip
+      outputJsonPath: ./appManifest/build/manifest.${{TEAMSFX_ENV}}.json
+  # Validate app package using validation rules
+  #- uses: teamsApp/validateAppPackage
+    #with:
+      # Relative path to this file. This is the path for built zip file.
+      #appPackagePath: ./appManifest/build/appManifest.${{TEAMSFX_ENV}}.zip
```
Comment (garrytrinder) [inline samples/cext-trey-research-python/teamsapp.local.yml:37]: Let's uncomment this action

File: samples/cext-trey-research-python/teamsapp.local.yml
Comment (garrytrinder) [inline samples/cext-trey-research-python/teamsapp.local.yml:1]: This file is missing the `teamsApp/extendToM365` action

File: samples/cext-trey-research-python/README.md [hunk 10]
```diff
@@ -0,0 +1,178 @@
...
+
+~~~text
+SECRET_STORAGE_ACCOUNT_CONNECTION_STRING=UseDevelopmentStorage=true
+~~~
+
+1. OPTIONAL: Copy the files from the **/sampleDocs** folder to OneDrive or SharePoint. Add the location of these files in the `OneDriveAndSharePoint` capability in the declarative copilot (**/appPackage/trey-declarative-copilot.json**).
+
+### Running the solution (after each build)
+
+> NOTE: This sample requires the private preview of Copilot for Microsoft 365 extensibility
```
Comment (garrytrinder) [inline samples/cext-trey-research-python/README.md:76]: This note can be removed as declarative agents are generally available

File: samples/cext-trey-research-python/README.md [hunk 11]
```diff
@@ -0,0 +1,178 @@
...
+
+1. Ensure the **Python extension** is installed in Visual Studio Code by searching for 'Python' in the Extensions view (Ctrl+Shift+X) and clicking Install.
+
+1. Press **CTRL+Shift+P** to open the command box and enter **Python: Create Environment** to create and activate your desired virtual environment.
+
+1. If your project doesn't yet have a file **env/.env.local.user**, then create one by copying **env/.env.local.user.sample**. If you do have such a file, ensure it includes these lines.
+
+~~~text
+SECRET_STORAGE_ACCOUNT_CONNECTION_STRING=UseDevelopmentStorage=true
+~~~
```
Comment (garrytrinder) [inline samples/cext-trey-research-python/README.md:70]: Let's add an action to the `teamapp.local.yml` file to create the `env.local.user` file when they start the app and remove this manual step.

File: samples/cext-trey-research-python/.vscode/launch.json [hunk 12]
```diff
@@ -0,0 +1,69 @@
+{
+    "version": "0.2.0",
+    "configurations": [
+        {
+            "name": "Launch App (Edge)",
+            "type": "msedge",
+            "request": "launch",
+            "url": "https://teams.microsoft.com/l/app/${{local:TEAMS_APP_ID}}?installAppPackage=true&webjoin=true&${account-hint}",
```
Comment (garrytrinder) [inline samples/cext-trey-research-python/.vscode/launch.json:8]: As this project contains a declarative agent, we should navigate to Microsoft 365 Copilot instead of Teams.

File: samples/cext-trey-research-python/.vscode/launch.json [hunk 13]
```diff
@@ -0,0 +1,69 @@
...
+                "group": "all",
+                "hidden": true
+            },
+            "internalConsoleOptions": "neverOpen"
+        },
+        {
+            "name": "Launch App (Chrome)",
+            "type": "chrome",
+            "request": "launch",
+            "url": "https://teams.microsoft.com/l/app/${{local:TEAMS_APP_ID}}?installAppPackage=true&webjoin=true&${account-hint}",
```
Comment (garrytrinder) [inline samples/cext-trey-research-python/.vscode/launch.json:22]: As this project contains a declarative agent, we should navigate to Microsoft 365 Copilot instead of Teams.

**Review by garrytrinder — CHANGES_REQUESTED** [review]
Let's address the comments.

After upgrading Python to 3.11, I am still getting an error when running the sample. 

```
Error: No module named 'azure.data', Cannot find module. Please check the requirements.txt file for the missing module. For more info, please refer the troubleshooting guide: https://aka.ms/functions-modulenotfound
```

File: samples/cext-trey-research-python/appManifest/manifest.json (hunk 2 above)
Comment (Jegadeesh-MSFT) [reply samples/cext-trey-research-python/appManifest/manifest.json:5]: Fixed

File: samples/cext-trey-research-python/appManifest/manifest.json [hunk 14]
```diff
@@ -0,0 +1,44 @@
+{
+  "$schema": "https://developer.microsoft.com/json-schemas/teams/vDevPreview/MicrosoftTeams.schema.json",
+  "manifestVersion": "devPreview",
```
[the remark this answers is not in the document]
Comment (Jegadeesh-MSFT) [reply samples/cext-trey-research-python/appManifest/manifest.json:3]: Fixed

File: samples/cext-trey-research-python/appManifest/manifest.json (hunk 4 above)
Comment (Jegadeesh-MSFT) [reply samples/cext-trey-research-python/appManifest/manifest.json:30]: Fixed

File: samples/cext-trey-research-python/appManifest/trey-declarative-copilot.json (hunk 5 above)
Comment (Jegadeesh-MSFT) [reply samples/cext-trey-research-python/appManifest/trey-declarative-copilot.json:2]: The json link provided above is giving error and so used the below one 
https://aka.ms/json-schemas/copilot/declarative-agent/v1.0/schema.json

File: samples/cext-trey-research-python/teamsapp.local.yml (hunk 8 above)
Comment (Jegadeesh-MSFT) [reply samples/cext-trey-research-python/teamsapp.local.yml:24]: Since our manifest shows an error in copilotExtensions, we need to comment out the validation part. We did this by following the example in [cext-trey-research-ts](https://github.com/Jegadeesh-MSFT/Copilot-for-M365-Samples/blob/v-jegadeesh/trey-sample-csharp/samples/cext-trey-research/teamsapp.yml#L51).

File: samples/cext-trey-research-python/teamsapp.local.yml (hunk 9 above)
Comment (Jegadeesh-MSFT) [reply samples/cext-trey-research-python/teamsapp.local.yml:37]: Since our manifest shows an error in copilotExtensions, we need to comment out the validation part. We did this by following the example in [cext-trey-research-ts](https://github.com/Jegadeesh-MSFT/Copilot-for-M365-Samples/blob/v-jegadeesh/trey-sample-csharp/samples/cext-trey-research/teamsapp.yml#L51).

File: samples/cext-trey-research-python/teamsapp.local.yml
Comment (Jegadeesh-MSFT) [reply samples/cext-trey-research-python/teamsapp.local.yml:1]: Fixed

File: samples/cext-trey-research-python/README.md (hunk 10 above)
Comment (Jegadeesh-MSFT) [reply samples/cext-trey-research-python/README.md:76]: Fixed

File: samples/cext-trey-research-python/README.md (hunk 11 above)
Comment (Jegadeesh-MSFT) [reply samples/cext-trey-research-python/README.md:70]: Fixed

File: samples/cext-trey-research-python/appManifest/trey-declarative-copilot.json (hunk 6 above)
Comment (Jegadeesh-MSFT) [reply samples/cext-trey-research-python/appManifest/trey-declarative-copilot.json:26]: Fixed

File: samples/cext-trey-research-python/appManifest/trey-declarative-copilot.json (hunk 7 above)
Comment (Jegadeesh-MSFT) [reply samples/cext-trey-research-python/appManifest/trey-declarative-copilot.json:6]: Tried it getting below error.

image

File: samples/cext-trey-research-python/.vscode/launch.json (hunk 12 above)
Comment (Jegadeesh-MSFT) [reply samples/cext-trey-research-python/.vscode/launch.json:8]: Please provide us with the link to be added here

File: samples/cext-trey-research-python/.vscode/launch.json (hunk 13 above)
Comment (Jegadeesh-MSFT) [reply samples/cext-trey-research-python/.vscode/launch.json:22]: Please provide us with the link to be added here

**Comment by Jegadeesh-MSFT** [comment]
> Let's address the comments.
> 
> After upgrading Python to 3.11, I am still getting an error when running the sample.
> 
> ```
> Error: No module named 'azure.data', Cannot find module. Please check the requirements.txt file for the missing module. For more info, please refer the troubleshooting guide: https://aka.ms/functions-modulenotfound
> ```

Hi @garrytrinder 

Iam unable to repro this issue. I have tested it with 3.11 v python as well

image

image

File: samples/cext-trey-research-python/.vscode/launch.json (hunk 12 above)
Comment (garrytrinder) [reply samples/cext-trey-research-python/.vscode/launch.json:8]: https://www.microsoft365.com/chat

File: samples/cext-trey-research-python/.vscode/launch.json (hunk 13 above)
Comment (garrytrinder) [reply samples/cext-trey-research-python/.vscode/launch.json:22]: [microsoft365.com/chat](https://www.microsoft365.com/chat)

File: samples/cext-trey-research-python/teamsapp.local.yml (hunk 8 above)
Comment (garrytrinder) [reply samples/cext-trey-research-python/teamsapp.local.yml:29]: The property was renamed to copilotAgents.

[learn.microsoft.com/microsoftteams/platform/resources/schema/manifest-schema#copilotagents](https://learn.microsoft.com/microsoftteams/platform/resources/schema/manifest-schema#copilotagents)

File: samples/cext-trey-research-python/appManifest/trey-declarative-copilot.json (hunk 7 above)
Comment (garrytrinder) [reply samples/cext-trey-research-python/appManifest/trey-declarative-copilot.json]: Did you include the `instruction.txt` file in the `appManifest` folder?

**Review by garrytrinder — CHANGES_REQUESTED** [review]
Thanks for the comments @Jegadeesh-MSFT 

Let's make some final adjustments.

File: samples/cext-trey-research-python/.vscode/launch.json (hunk 13 above)
Comment (Jegadeesh-MSFT) [reply samples/cext-trey-research-python/.vscode/launch.json:22]: Fixed

File: samples/cext-trey-research-python/.vscode/launch.json (hunk 12 above)
Comment (Jegadeesh-MSFT) [reply samples/cext-trey-research-python/.vscode/launch.json:8]: fixed

File: samples/cext-trey-research-python/appManifest/trey-declarative-copilot.json (hunk 7 above)
Comment (Jegadeesh-MSFT) [reply samples/cext-trey-research-python/appManifest/trey-declarative-copilot.json]: Yes, I did. It didn't recognize it.

**Comment by garrytrinder** [comment]
@Jegadeesh-MSFT I followed the instructions in the readme, however I get the following error when running F5 for the first time in Visual Studio Code.

```
[2025-01-23T16:40:10.332Z] [Info] - Executing lifecycle provision
[2025-01-23T16:40:15.950Z] [Error] - Failed to Execute lifecycle provision due to failed action: script. ScriptExecutionError:Execute command failure: echo "::set-teamsfx-env SECRET_STORAGE_ACCOUNT_CONNECTION_STRING=***=true >> ./env/.env.local.user. Env output: {"TEAMS_APP_ID":"<redacted>","TEAMS_APP_TENANT_ID":"<redacted>"}
[2025-01-23T16:40:15.951Z] [Info] - Execution summary:

Summary:
(×) Error: Lifecycle stage provision failed.
  (√) Done: teamsApp/create was executed successfully.
    (√) Done: Teams app <redacted> created successfully
  (×) Error: script failed.
    (×) Error: Execute command failure: echo "::set-teamsfx-env SECRET_STORAGE_ACCOUNT_CONNECTION_STRING=***=true >> ./env/.env.local.user
  (!) Warning: teamsApp/zipAppPackage was not executed.
  (!) Warning: teamsApp/update was not executed.
  (!) Warning: teamsApp/extendToM365 was not executed.
```

**Comment by Jegadeesh-MSFT** [comment]
> @Jegadeesh-MSFT I followed the instructions in the readme, however I get the following error when running F5 for the first time in Visual Studio Code.
> 
> ```
> [2025-01-23T16:40:10.332Z] [Info] - Executing lifecycle provision
> [2025-01-23T16:40:15.950Z] [Error] - Failed to Execute lifecycle provision due to failed action: script. ScriptExecutionError:Execute command failure: echo "::set-teamsfx-env SECRET_STORAGE_ACCOUNT_CONNECTION_STRING=***=true >> ./env/.env.local.user. Env output: {"TEAMS_APP_ID":"<redacted>","TEAMS_APP_TENANT_ID":"<redacted>"}
> [2025-01-23T16:40:15.951Z] [Info] - Execution summary:
> 
> Summary:
> (×) Error: Lifecycle stage provision failed.
>   (√) Done: teamsApp/create was executed successfully.
>     (√) Done: Teams app <redacted> created successfully
>   (×) Error: script failed.
>     (×) Error: Execute command failure: echo "::set-teamsfx-env SECRET_STORAGE_ACCOUNT_CONNECTION_STRING=***=true >> ./env/.env.local.user
>   (!) Warning: teamsApp/zipAppPackage was not executed.
>   (!) Warning: teamsApp/update was not executed.
>   (!) Warning: teamsApp/extendToM365 was not executed.
> ```

Hi @garrytrinder ,

I tried the sample but was unable to reproduce the issue. Please find the video attached below.

https://github.com/user-attachments/assets/59f5233b-e3a2-48ef-82eb-570b9a1ecdd6

Thanks

File: samples/cext-trey-research-python/README.md [hunk 15]
```diff
@@ -0,0 +1,170 @@
...
+
+## Setup
+
+### Prerequisites
+
+* [Python 3.11.x](https://www.python.org/downloads/)
+* [Visual Studio Code](https://code.visualstudio.com/Download)
+* [NodeJS 18.x](https://nodejs.org/en/download)
+* [Teams Toolkit extension for VS Code](https://marketplace.visualstudio.com/items?itemName=TeamsDevApp.ms-teams-vscode-extension)
+  NOTE: If you want to build new projects of this nature, you'll need Teams Toolkit v5.6.1-alpha.039039fab.0 or newer
```
Comment (garrytrinder) [inline samples/cext-trey-research-python/README.md:53]: This note isn't required anymore, so let's remove it.

File: samples/cext-trey-research-python/README.md [hunk 16]
```diff
@@ -0,0 +1,170 @@
...
+  1. API based plugin works with any platform that supports REST requests
+  1. Copilot will construct queries for specific data using GET requests
+  1. Copilot updates and adds data using POST requests
+  1. Multi-parameter queries to filter results
+  1. Show a confirmation card before POSTing data; capture missing parameters
+  1. Display rich adaptive cards
+
+## Setup
+
+### Prerequisites
```
Comment (garrytrinder) [inline samples/cext-trey-research-python/README.md:47]: We are missing Azure Functions Core Tools v4 in this list.

File: samples/cext-trey-research-python/README.md [hunk 17]
```diff
@@ -0,0 +1,170 @@
...
+* [Python 3.11.x](https://www.python.org/downloads/)
+* [Visual Studio Code](https://code.visualstudio.com/Download)
+* [NodeJS 18.x](https://nodejs.org/en/download)
+* [Teams Toolkit extension for VS Code](https://marketplace.visualstudio.com/items?itemName=TeamsDevApp.ms-teams-vscode-extension)
+  NOTE: If you want to build new projects of this nature, you'll need Teams Toolkit v5.6.1-alpha.039039fab.0 or newer
+* [Teams Toolkit CLI](https://learn.microsoft.com/microsoftteams/platform/toolkit/teams-toolkit-cli?pivots=version-three)
+  (`npm install -g @microsoft/teamsapp-cli`)
+* (optional) [Postman](https://www.postman.com/downloads/)
+
+### Setup instructions (one-time setup)
```
Comment (garrytrinder) [inline samples/cext-trey-research-python/README.md:58]: These instructions are missing updating the `TENANT_NAME` environment variable in `env/.env.local` file. I got an error when running F5.

`[Error] - Failed to Execute lifecycle provision due to failed action: teamsApp/zipAppPackage. MissingEnvironmentVariablesError:Missing environment variables 'TENANT_NAME' for file: /**redacted**/appManifest/trey-declarative-agent.json. Please edit the .env file '/**redacted**/env/.env.local' or '/**redacted**/env/.env.local.user', or adjust system environment variables. For new Teams Toolkit projects, make sure you've run provision or debug to set these variables correctly.. Env output: {"TEAMS_APP_ID":"**redacted**","TEAMS_APP_TENANT_ID":"**redacted**","SECRET_STORAGE_ACCOUNT_CONNECTION_STRING":"******"}`

File: samples/cext-trey-research-python/teamsapp.local.yml [hunk 18]
```diff
@@ -0,0 +1,68 @@
...
+      name: cexttreyresearch${{APP_NAME_SUFFIX}}
+    # Write the information of created resources into environment file for
+    # the specified environment variable(s).
+    writeToEnvironmentFile: 
+      teamsAppId: TEAMS_APP_ID
+
+  - uses: script 
+    with:
+      run:
+        echo "::set-teamsfx-env SECRET_STORAGE_ACCOUNT_CONNECTION_STRING=UseDevelopmentStorage=true >> ./env/.env.local.user
```
Comment (garrytrinder) [inline samples/cext-trey-research-python/teamsapp.local.yml:23]: The echo command is missing the closing quote and so throws an error.

```suggestion
        echo "::set-teamsfx-env SECRET_STORAGE_ACCOUNT_CONNECTION_STRING=UseDevelopmentStorage=true" >> ./env/.env.local.user
```

**Review by garrytrinder — APPROVED** [review]
@Jegadeesh-MSFT I'm still having issues running this sample, see comments for fixes I had to make to get this far.

I am now facing this issue.

image

File: samples/cext-trey-research-python/app.py [hunk 19]
```diff
@@ -0,0 +1,40 @@
...
+        try:
+            # Run the Azure Functions host using the subprocess module to call 'func start'
+            subprocess.run([func_path, "start"], shell=True, check=True)
+        except subprocess.CalledProcessError as e:
+            print(f"Error occurred while running Azure Functions: {e}")
+            sys.exit(1)
+    else:
+        print("Azure Functions Core Tools (func) not found in your system PATH.")
+        print("Please install it or ensure it's available in the PATH.")
+        sys.exit(1)
```
Comment (garrytrinder) [inline samples/cext-trey-research-python/app.py:33]: image

**Review by garrytrinder — CHANGES_REQUESTED** [review]

File: samples/cext-trey-research-python/README.md (hunk 15 above)
Comment (Jegadeesh-MSFT) [reply samples/cext-trey-research-python/README.md:53]: Fixed

File: samples/cext-trey-research-python/README.md (hunk 16 above)
Comment (Jegadeesh-MSFT) [reply samples/cext-trey-research-python/README.md:47]: Fixed

File: samples/cext-trey-research-python/README.md (hunk 17 above)
Comment (Jegadeesh-MSFT) [reply samples/cext-trey-research-python/README.md:58]: Fixed

File: samples/cext-trey-research-python/teamsapp.local.yml (hunk 18 above)
Comment (Jegadeesh-MSFT) [reply samples/cext-trey-research-python/teamsapp.local.yml:23]: Fixed

File: samples/cext-trey-research-python/app.py (hunk 19 above)
Comment (garrytrinder) [reply samples/cext-trey-research-python/app.py:33]: I noticed that `azure-functions` is listed as a dependency in the `requirements.txt` file. Is this installed when I create the Python environment in VSCode? Or is there a step missing in the instructions?

Comment (Jegadeesh-MSFT) [reply samples/cext-trey-research-python/app.py:33]: Please try the updated code. If the issue still persists, please provide me with the Python version to check further.

File: samples/cext-trey-research-python/app.py [hunk 20]
```diff
@@ -0,0 +1,40 @@
...
+    # Check if 'func' is in PATH
+    func_path = shutil.which("func")
+    
+    if func_path:
+        # Change directory to where your Azure Functions app is located
+        os.chdir('functions')  # Adjust 'functions' if needed to match your directory structure
+
+        try:
+            # Run the Azure Functions host using the subprocess module to call 'func start'
+            subprocess.run([func_path, "start"], shell=True, check=True)
```
Comment (garrytrinder) [inline samples/cext-trey-research-python/app.py:26]: This function does not call `func start` correctly and instead calls `func`. When using the latest version of Azure Functions Core Tools, v4.0.6821, this results in the runtime not starting correctly and displaying the following message.

> You are using an old Core Tools version. Please upgrade to the latest version.

Related issue: https://github.com/Azure/azure-functions-core-tools/issues/4235

```suggestion
            subprocess.run([func_path, "start"], check=True)
```

The shell=True argument in subprocess.run can be a security risk, especially if any part of the command string is constructed from external input. It is generally safer to avoid using shell=True unless absolutely necessary. Consider removing shell=True and passing the command as a list of arguments.

**Review by garrytrinder — CHANGES_REQUESTED** [review]

File: samples/cext-trey-research-python/app.py (hunk 20 above)
Comment (Jegadeesh-MSFT) [reply samples/cext-trey-research-python/app.py]: Fixed

**Review by garrytrinder — APPROVED** [review]
